name: Test

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php-versions: [ '7.4', '8.0' ]
    steps:
      - uses: actions/checkout@master
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-ansi --no-progress
      - name: PHPUnit
        run: vendor/bin/phpunit
